CREATE schema ensino;
CREATE TABLE ensino.aluno (
	codigo serial NOT NULL,
	cpf character varying(255),	
	nome character varying(255),
	sexo character varying(10),
	escolaridade character varying(100),
	escolaridade_descr character varying(100),
	naturalidade_codigo bigint,
	naturalidade_nome character varying(50),
	data_nascimento DATE,
	religiao character varying(255),
	religiao_descr character varying(100),
	origem_escolar character varying(255),
	origem_escolar_descr character varying(100),
	colegio_militar character varying(255),
	colegio_militar_descr character varying(100),
	etnia character varying(255),
	etnia_descr character varying(100),
	origem_civil_militar character varying(255),
	origem_civil_militar_descr character varying(100),
	origem_fab character varying(100),
    origem_eb character varying(100),
    origem_mb character varying(100),
	origem_militar character varying(255),	
	paises_descr character varying(100),
	paises character varying(255),	
	renda_familiar character varying(100),
	renda_familiar_descr character varying(100),	
	seg_grad_pos character varying(100),
	cotista character varying(50),	
	pai_mae_militar character varying(50),
	dados_inseridos_por bigint,
	ativo boolean DEFAULT true NOT NULL,
	foto character varying(100),
	content_type character varying(100),
			
	CONSTRAINT aluno_pkey PRIMARY KEY (codigo),	
	UNIQUE (cpf)
	
);
