package br.mil.eb.decex.sisaluno.enumerated;

public enum Paises {
	
	ACROTIRI_E_DECELEIA("Acrotiri e Deceleia"),
	ACORES("Açores"),
	ABECASIA("Abecásia"),
	AFEGANISTAO("Afeganistão"),
	AFRICA_DO_SUL("África do Sul"),
	ALBANIA("Albânia"),
	ALEMANHA("Alemanha"),
	ANDORRA("Andorra"),
	ANGOLA("Angola"),
	ANGUILA("Anguila"),
	ANTARTIDA("Antártida"),
	ANTIGUA_E_BARBUDA("Antigua e Barbuda"),
	ARABIA_SAUDITA("Arábia Saudita"),
	ARGELIA("Argélia"),
	ARGENTINA("Argentina"),
	ARMENIA("Arménia"),
	ARUBA("Aruba"),
	AUSTRALIA("Austrália"),
	AUSTRIA("Áustria"),
	AZEBURJAO("Azerbaijão"),
	BAHAMAS("Bahamas"),
	BANGLADEXE("Bangladexe"),
	BARBADOS("Barbados"),
	BAREM("Barém"),
	BELGICA("Bélgica"),
	BELIZE("Belize"),
	BENIM("Benim"),
	BIELORRUSIA("Bielorrússia"),
	BOLIVIA("Bolívia"),
	BONAIRE("Bonaire"),
	BOSNIA_E_HERZEGOVINA("Bósnia e Herzegovina"),
	BOTSUANA("Botsuana"),
	BRASIL("Brasil"),
	BRUNEL("Brunei"),
	BULGARIA("Bulgária"),
	BURQUINA_FASO("Burquina Faso"),
	BURUNDI("Burúndi"),
	BUTAO("Butão"),
	CABO_VERDE("Cabo Verde"),
	CAMAROES("Camarões"),
	CAMBOJA("Camboja"),
	CANADA("Canadá"),
	CANARIAS("Canárias"),
	CATAR("Catar"),
	CAZAQUISTAO("Cazaquistão"),
	CHADE("Chade"),
	CHILE("Chile"),
	CHINA("China"),
	CHIPRE("Chipre"),
	COLOMBIA("Colômbia"),
	COMORES("Comores"),
	CONGO_BRAZZAVILLE("Congo-Brazzaville"),
	COREIA_DO_NORTE("Coreia do Norte"),
	COREIA_DO_SUL("Coreia do SuL"),
	COSOVO("Cosovo"),
	COSTA_DO_MARFIM("Costa do Marfim"),
	COSTA_RICA("Costa Rica"),
	CROACIA("Croácia"),
	CUAITE("Cuaite"),
	CUBA("Cuba"),
	DINAMARCA("Dinamarca"),
	DOMINICA("Dominica"),
	EGITO("Egito"),
	EMIRADOS_ARABES_UNIDOS("Emirados Árabes Unidos"),
	EQUADOR("Equador"),
	ESTREIA("Eritreia"),
	ESLOVAQUIA("Eslováquia"),
	ESLOVENIA("Eslovénia"),
	ESPANHA("Espanha"),
	ESSUATINI("Essuatíni"),
	ESTADO_DA_PALESTINA("Estado da Palestina"),
	ESTADOS_UNIDOS("Estados Unidos"),
	ESTONIA("Estónia"),
	ETIOPIA("Etiópia"),
	FIGI("Fiji"),
	FILIPINAS("Filipinas"),
	FINLANDIA("Finlândia"),
	FRANCA("França"),
	GABAO("Gabão"),
	GAMBIA("Gâmbia"),
	GANA("Gana"),
	GEORGIA("Geórgia"),
	GRANADA("Granada"),
	GRECIA("Grécia"),
	GUATEMALA("Guatemala"),
	GUIANA("Guiana"),
	GUINE("Guiné"),
	GUINE_EQUATORIAL("Guiné Equatorial"),
	GUINE_BISSAU("Guiné-Bissau"),
	HAITI("Haiti"),
	HONDURAS("Honduras"),
	HUNGRIA("Hungria"),
	IEMEN("Iémen"),
	ILHAS_MARECHAL("Ilhas Marechal"),
	INDIA("Índia"),
	INDONÉSIA("Indonésia"),
	IRAO("Irão"),
	IRAQUE("Iraque"),
	IRLANDA("Irlanda"),
	ISLANDIA("Islândia"),
	ISRAEL("Israel"),
	ITALIA("Itália"),
	JAMAICA("Jamaica"),
	JAPAO("Japão"),
	JIBUTI("Jibuti"),
	JORDANIA("Jordânia"),
	LAUS("Laus"),
	LESOTO("Lesoto"),
	LETONIA("Letónia"),
	LIBANO("Líbano"),
	LIBERIA("Libéria"),
	LIBIA("Líbia"),
	LITENSTAINE("Listenstaine"),
	LITUANIA("Lituânia"),
	LUXEMBURGO("Luxemburgo"),
	MACEDONIA_DO_NORTE("Macedónia do Norte"),
	MADAGASCAR("Madagáscar"),
	MALASIA("Malásia"),
	MALAUI("Maláui"),
	MALDIVAS("Maldivas"),
	MALI("Mali"),
	Malta("Malta"),
	MARROCOS("Marrocos"),
	MAURICIA("Maurícia"),
	MAURITANIA("Mauritânia"),
	MEXICO("México"),
	MIANMAR("Mianmar"),
	MICRONESIA("Micronésia"),
	MOCAMBIQUE("Moçambique"),
	MOLDAVIA("Moldávia"),
	MONACO("Mónaco"),
	MONGOLIA("Mongólia"),
	MONTENEGRO("Montenegro"),
	NAMIBIA("Namíbia"),
	NAURU("Nauru"),
	NEPAL("Nepal"),
	NICARAGUA("Nicarágua"),
	NIGER("Níger"),
	NIGERIA("Nigéria"),
	NORUEGA("Noruega"),
	NOVA_ZELANDIA("Nova Zelândia"),
	OMA("Omã"),
	PAISES_BAIXOS("Países Baixos"),
	PALAU("Palau"),
	PANAMA("Panamá"),
	PAPUA_NOVA_GUINE("Papua Nova Guiné"),
	PAQUISTAO("Paquistão"),
	PARAGUAI("Paraguai"),
	PERU("Peru"),
	POLONIA("Polónia"),
	PORTUGAL("Portugal"),
	QUENIA("Quénia"),
	QUIRGUISTAO("Quirguistão"),
	QUIRIBATI("Quiribáti"),
	REINO_UNIDO("Reino Unido"),
	REPUBLICA_CENTRO_AFRICANA("República Centro-Africana"),
	REPUBLICA_CHECA("República Checa"),
	REPUBLICA_DEMOCRATICA_DO_CONGO("República Democrática do Congo"),
	REPUBLICA_DOMINICANA("República Dominicana"),
	ROMENIA("Roménia"),
	RUANDA("Ruanda"),
	RUSSIA("Rússia"),
	SALOMAO("Salomão"),
	SALVADOR("Salvador"),
	SAMOA("Samoa"),
	SANTA_LUCIA("Santa Lúcia"),
	SAO_CRISTOVAO_E_NEVES("São Cristóvão e Neves"),
	SAO_MARINHO("São Marinho"),
	SAO_TOME_E_PRINCIPE("São Tomé e Príncipe"),
	SAO_VICENTE_E_GRANADINAS("São Vicente e Granadinas"),
	SEICHELES("Seicheles"),
	SENEGAL("Senegal"),
	SERRA_LEOA("Serra Leoa"),
	SERVIA("Sérvia"),
	SINGAPURA("Singapura"),
	SIRIA("Síria"),
	SOMALIA("Somália"),
	SRI_LANCA("Sri Lanca"),
	SUDAO("Sudão"),
	SUDAO_DO_SUL("Sudão do Sul"),
	SUECIA("Suécia"),
	SUICA("Suíça"),
	SURINAME("Suriname"),
	TAILANDIA("Tailândia"),
	TAIUA("Taiuã"),
	TAJIQUISTAO("Tajiquistão"),
	TANZANIA("Tanzânia"),
	TIMOR_LESTE("Timor-Leste"),
	TOGO("Togo"),
	TONGA("Tonga"),
	TRINIDADE_E_TOBAGO("Trinidade e Tobago"),
	TUNISIA("Tunísia"),
	TURCOMENISTAO("Turcomenistão"),
	TURQUIA("Turquia"),
	TUVALU("Tuvalu"),
	UCRANIA("Ucrânia"),
	UGANDA("Uganda"),
	URUGUAI("Uruguai"),
	USBEQUISTAO("Usbequistão"),
	VANUATU("Vanuatu"),
	VATICANO("Vaticano"),
	VENEZUELA("Venezuela"),
	VIETNAME("Vietname"),
	ZAMBIA("Zâmbia"),
	ZIMBABUE("Zimbábue");


	
	private String descricao;
	
	Paises(String descricao) {
		this.descricao = descricao;
	}

	public String getDescricao() {
		return descricao;
	}
}
